version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8054:8054"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8054
    networks:
      - ai-scanner-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8054
    networks:
      - ai-scanner-network

networks:
  ai-scanner-network:
    driver: bridge
